export const DISCLAIMER_STORAGE_KEY = "etfvision_disclaimer_v1";

export const FULL_DISCLAIMER_TEXT = `ETFVision provides deterministic analytical scores and portfolio metrics for informational purposes only. Nothing on this platform constitutes investment advice, a recommendation to buy or sell any security, or a solicitation of any investment transaction.

All outputs — including Characteristics Scores, Portfolio Scores, Confidence metrics, Assessment labels (Good, Neutral, Weak), Guardrail classifications, and Gap Analysis findings — are deterministic analytical classifications derived from quantitative data inputs. They are not ratings, opinions, or recommendations under any securities law or regulation.

Past scores are not indicative of future performance, returns, or outcomes. ETFVision does not manage client assets, hold client funds, or execute trades.

Consult a licensed financial adviser before making any investment decision.`;

export const FOOTER_DISCLAIMER_TEXT =
  "Scores and analytics are for informational purposes only. Not investment advice. Not a recommendation to buy or sell any security. Consult a licensed financial adviser.";

export const EXPORT_REPORT_DISCLAIMER_TEXT =
  "Generated by ETFVision for informational and analytical purposes only. Does not constitute investment advice, a buy or sell recommendation, or a solicitation for any transaction. All scores are deterministic analytical outputs. Consult a qualified financial adviser before acting on any information in this report.";
