-- Portfolio analytics history foundation.
-- Snapshots are generated by application services and remain portable across Supabase and Cloud SQL.

create table if not exists portfolio_snapshots (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references portfolios(id) on delete cascade,
  snapshot_date date not null,
  total_value numeric(28, 10) not null,
  cash_value numeric(28, 10) not null default 0,
  invested_value numeric(28, 10) not null default 0,
  unrealized_gain_loss numeric(28, 10) not null default 0,
  realized_gain_loss numeric(28, 10) not null default 0,
  currency text not null,
  asset_class_allocations jsonb not null default '{}',
  sector_allocations jsonb not null default '{}',
  geography_allocations jsonb not null default '{}',
  currency_allocations jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (portfolio_id, snapshot_date)
);

create table if not exists asset_snapshots (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references portfolios(id) on delete cascade,
  asset_id uuid not null references assets(id) on delete cascade,
  snapshot_date date not null,
  quantity numeric(28, 10) not null,
  market_price numeric(28, 10),
  market_value numeric(28, 10) not null default 0,
  cost_basis numeric(28, 10),
  unrealized_gain_loss numeric(28, 10),
  currency text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (portfolio_id, asset_id, snapshot_date)
);

create index if not exists idx_portfolio_snapshots_portfolio_date on portfolio_snapshots (portfolio_id, snapshot_date desc);
create index if not exists idx_asset_snapshots_portfolio_date on asset_snapshots (portfolio_id, snapshot_date desc);
create index if not exists idx_asset_snapshots_asset_date on asset_snapshots (asset_id, snapshot_date desc);

drop trigger if exists trg_portfolio_snapshots_updated_at on portfolio_snapshots;
create trigger trg_portfolio_snapshots_updated_at before update on portfolio_snapshots for each row execute function set_updated_at();

drop trigger if exists trg_asset_snapshots_updated_at on asset_snapshots;
create trigger trg_asset_snapshots_updated_at before update on asset_snapshots for each row execute function set_updated_at();

alter table portfolio_snapshots enable row level security;
alter table asset_snapshots enable row level security;

create policy "users can read own portfolio snapshots" on portfolio_snapshots
  for select using (
    exists (
      select 1 from portfolios
      join users on users.id = portfolios.user_id
      where portfolios.id = portfolio_snapshots.portfolio_id
        and users.auth_provider = 'supabase'
        and users.auth_provider_user_id = auth.uid()::text
    )
  );

create policy "users can read own asset snapshots" on asset_snapshots
  for select using (
    exists (
      select 1 from portfolios
      join users on users.id = portfolios.user_id
      where portfolios.id = asset_snapshots.portfolio_id
        and users.auth_provider = 'supabase'
        and users.auth_provider_user_id = auth.uid()::text
    )
  );
