-- Holding performance history foundation.
-- Snapshots are generated by application services and remain portable across Supabase and Cloud SQL.

create table if not exists holding_snapshots (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references portfolios(id) on delete cascade,
  holding_id uuid not null references holdings(id) on delete cascade,
  asset_id uuid not null references assets(id) on delete cascade,
  snapshot_date date not null,
  quantity numeric(28, 10) not null,
  market_price numeric(28, 10),
  market_value numeric(28, 10) not null default 0,
  cost_basis numeric(28, 10),
  unrealized_gain_loss numeric(28, 10),
  currency text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (portfolio_id, holding_id, snapshot_date)
);

create index if not exists idx_holding_snapshots_portfolio_date on holding_snapshots (portfolio_id, snapshot_date desc);
create index if not exists idx_holding_snapshots_holding_date on holding_snapshots (holding_id, snapshot_date desc);
create index if not exists idx_holding_snapshots_asset_date on holding_snapshots (asset_id, snapshot_date desc);

drop trigger if exists trg_holding_snapshots_updated_at on holding_snapshots;
create trigger trg_holding_snapshots_updated_at before update on holding_snapshots for each row execute function set_updated_at();

alter table holding_snapshots enable row level security;

create policy "users can read own holding snapshots" on holding_snapshots
  for select using (
    exists (
      select 1 from portfolios
      join users on users.id = portfolios.user_id
      where portfolios.id = holding_snapshots.portfolio_id
        and users.auth_provider = 'supabase'
        and users.auth_provider_user_id = auth.uid()::text
    )
  );
